plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
	id "maven-publish"
}

version = "${mod_version}+mc${minecraft_version}"
group = maven_group

base {
	archivesName = "${archives_base_name}-fabric"
}

sourceSets {
	main {
		java.srcDirs = ["common/src/main/java", "fabric/src/main/java"]
		resources.srcDirs = ["common/src/main/resources", "fabric/src/main/resources"]
	}
}

loom {
	accessWidenerPath = file("common/src/main/resources/villagertradingplus.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

processResources {
	def v = project.version
	inputs.property "version", v
	filesMatching("fabric.mod.json") {
		expand "version": v
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		mavenFabric(MavenPublication) {
			artifactId = "${archives_base_name}-fabric"
			from components.java
		}
	}
}
