org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

mod_id=villagertradingplus

archives_base_name=villagertradingplus
mod_version=1.0.0
maven_group=lion.villagertradingplus

architectury_version=13.0.6

fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1

neoforge_version=21.1.247

yarn_mappings=1.21.1+build.3:v2
yarn_mappings_patch_neoforge_version=1.21+build.6
